export const VALUES_CALC = [
  { text: 'AC', type: 'action' },
  { text: '+/-', type: 'action' },
  { text: '%', type: 'action' },
  { text: '/', type: 'operation' },
  { text: '7', type: 'number' },
  { text: '8', type: 'number' },
  { text: '9', type: 'number' },
  { text: '*', type: 'operation' },
  { text: '4', type: 'number' },
  { text: '5', type: 'number' },
  { text: '6', type: 'number' },
  { text: '-', type: 'operation' },
  { text: '1', type: 'number' },
  { text: '2', type: 'number' },
  { text: '3', type: 'number' },
  { text: '+', type: 'operation' },
  { text: '0', type: 'number' },
  { text: '.', type: 'number' },
  { text: '=', type: 'operation' },
];